Base abstract version
ShaharBand/Sentinel pull request #1
Opened 2024-01-31 17:09 UTC by ShaharBand

A basic skeleton for the project with somewhat working backend structure.

i still need to impelement the frontend and the application logic.

2024-02-03 14:54 UTC, KobieHazon reviewed
Won't review the frontend now because I don't have the time.
Later but you have a lot to fix but good job!

2024-02-03 14:54 UTC, KobieHazon commented on README.md
> +[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
Make sure they know :)

2024-02-03 14:54 UTC, KobieHazon commented on .gitignore
> +.idea/
add newline, make your editor do this automatically

2024-02-03 14:54 UTC, KobieHazon commented on backend/main.py
> +from fastapi import FastAPI
order imports like you should in python

2024-02-03 14:54 UTC, KobieHazon commented on backend/main.py
> +    import uvicorn
Nooo
I really don't like imports inside functions or classes, usually bad

2024-02-03 14:54 UTC, KobieHazon commented on backend/main.py
> +def run_uvicorn():
give it a name better its affect, like run_server

2024-02-03 14:54 UTC, KobieHazon commented on backend/main.py
> +    uvicorn.run("main:app", reload=True, host="127.0.0.1", port=8000)
IP and port are strong magic values

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/controllers/test.py
> +print(device)
this is not a test, read how to write tests using pytest

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/dal/devices.py
> +from backend.src.utils.config import config
imports order, will not comment about it again so make sure

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/dal/devices.py
> +db.define_table('devices',
I don't like pydal, maybe you do but I think this syntax is pretty ugly.

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/dal/users.py
> +
I understand why you put those link breaks but they shouldn't be here and don't add to the readability.

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/device.py
> +from pydantic import BaseModel, StrictStr, IPvAnyAddress
cool, I didn't use the last class here.

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/device.py
> +    data: DeviceData
commented in whatsapp that this is not really a good implementation of abstract property.

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/device.py
> +class Device(ABC):
It looks like there is a nice coupling between the device and the devicedata, consider making it a generic

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/device.py
> +        pass
no empty line at end of file

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/devices/linux.py
It is better if you intend to do something in the future to not write an empty file but write a TODO: comment
the editor will also make a special color to this word and you can search for it easily.

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/devices/windows.py
> +        else:
remove this else, better to put it only if it is necessary to understand the flow

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/devices/windows.py
> +        updated_rows = db(db.devices.name == self.data.name).update(
split to two different lines (condition and update). not readable enough

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/devices/windows.py
> +        else:
same as before, won't comment again

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/devices/windows.py
> +        deleted_rows = db(db.devices.name == self.data.name).delete()
same as before, won't comment again

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/devices/windows.py
> +            result = subprocess.run(["ping", "-n", "1", str(self.data.address)], capture_output=True, text=True,
put the ping command in a consts.py file

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/user.py
> +
The empty lines are nice here, not in the DAL :)

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/models/user.py
> +        pass
write TODOOO

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/routers/devices.py
> +    pass
new line, won't comment again

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/services/devices.py
> +def get_all_devices() -> List:
which python version? if more then 3.8, use list without import from typing, also type the content of the list :)

2024-02-03 14:54 UTC, KobieHazon commented on backend/src/utils/config.py
> +    def DB_URI(self) -> str:
Don't do it here, it isn't part of the configuration, needs to be elsewhere

2024-02-03 14:54 UTC, KobieHazon commented on backend/tests/integration/test_devices_integration.py
> +import unittest
pytest is better

2024-02-03 14:54 UTC, KobieHazon commented on backend/tests/integration/test_devices_integration.py
> +        # Insert the device into the database
Comments are not needed if the code explains itself

2024-02-03 20:22 UTC, ShaharBand commented on README.md
> +[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)
No need to register it is advised to add a LICENSE file in the repo you can do that through git so this one has been resolved.

2024-02-04 08:41 UTC, ShaharBand commented on backend/main.py
> +from fastapi import FastAPI
```
import uvicorn

from fastapi import FastAPI

from backend.src.routers import users_router
from backend.src.routers import devices_router
```

i hope this is what you had in mind it is the logic i found to be correct in the internet

2024-02-04 09:14 UTC, ShaharBand commented on backend/src/models/device.py
> +class Device(ABC):
I like this idea alot but i still dont know what kind of devices i will encounter other than linux and windows there is a probability for routers / network devices but i am not quite sure if its in my current project scope..

for the future i will integrate it very nice comment :)

2024-02-04 09:23 UTC, ShaharBand commented on backend/src/models/devices/windows.py
> +        else:
i also shortened the code thank you

2024-02-04 09:24 UTC, ShaharBand commented on backend/src/models/devices/linux.py
cool didnt know

2024-02-04 11:50 UTC, ShaharBand reviewed
Changes have been updated

2024-02-10 10:27 UTC, KobieHazon commented
General comment: only the one giving you the review should resolve the comment he says to see that he is satisfied with the solution.
You can write: DONE, changed, or something like that

2024-02-10 10:47 UTC, KobieHazon reviewed
Second review on backend, don't resolve my comments :(

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/dal/devices.py
> +@lru_cache()
I think that if you don't use the maxsize argument than you don't need the parentheses and you probably should use the maxsize to make sure you don't get OOM error

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/dal/devices.py
> +    if config.MOCK_DB:
Combining test and production code in the same place is a big nono, think and read online how to do it differently, pytest offers a lot of ways.
For integration tests, you really should use a real DB and for that running using a docker-compose file will be really good. but that is an advanced task.

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/dal/users.py
> +# TODO: mock db
No, like last comment

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/devices/device.py
> +    def id(self) -> int | None:
most times, ID can just be implemented in the base class because it is very common and backendy logic

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/devices/device.py
> +    @abstractmethod
why is it abstract?
almost always, protected functions should not be abstract.

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/devices/device_factory.py
> +    def create_device(device_record: dict) -> Device | None:
that is a really ugly way to pass parameters and bypasses the checks of the IDE.
try to characterize the arguments you need to pass and maybe make an init in the abstract class that will be super-called in the inheriting ones.
the stuff that are not common between the devices can be passed using a kwargs argument

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/devices/device_factory.py
> +        if "windows" in os_type:
Magic, make a dict map from os_type to class

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/devices/windows_device.py
> +        query = (db.devices.id == self.id)
why two queries for a simple update? IO requests are expensive, try to do in one.

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/devices/windows_device.py
> +            inserted_id = db.devices.insert(**dict(self.data))
maybe make the data a BaseModel so it will be more ensured that it can convert easily to dictionary?

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/models/user.py
> +    def __init__(self, **args):
try to avoid kwargs when don't need, really bad practice avoid type and name checking before runtime.

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/routers/users.py
> +router = APIRouter()
use the APIRouter like a pro and not a noob, always avoid code duplication
'''router = APIRouter(
    prefix="/items",
    tags=["items"],
    dependencies=[Depends(get_token_header)],
    responses={404: {"description": "Not found"}},
)
''' # an example

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/services/devices.py
> +    return devices if devices else None
I think it makes more sense to return an empty list

2024-02-10 10:47 UTC, KobieHazon commented on backend/src/utils/config.py
> +class AppConfigManager:
It will be nice if it will have the option to return an instance of config according to the runtime environment, imagine you can an integ, prod or stuff like that, maybe even for some tests.

2024-02-10 14:14 UTC, ShaharBand commented on backend/src/dal/devices.py
> +@lru_cache()
Instead, after abit of investigating using a function like `@functools.singleton`, seems more ideal :) i hope this will satisfy your request.

2024-02-10 14:51 UTC, ShaharBand commented on backend/src/models/devices/device_factory.py
> +        if "windows" in os_type:
changed

2024-02-10 14:52 UTC, ShaharBand commented on backend/src/services/devices.py
> +    return devices if devices else None
changed

2024-02-16 23:22 UTC, KobieHazon requested changes
I am having a hard time reading the code because it uses many very old and not recommended conventions, so I will write in a few general points to the entire code:
1. couple between the code and the css by using styled-components.
2. stop declaring all functions as lambda in a const, it is just worse to read.
3. as a developer, you want to touch the lowest level interface with html as possible, thus, component libraries wrap them up in a very good way and allow you to avoid 90% of the css and other stuff you did here, read about the mui component library more. Especially the layout section of it.

Go Ahead Champ!

2024-02-16 23:22 UTC, KobieHazon commented on frontend/src/components/DevicesContainer/style.css
> +    background: var(--secondary-color);
styled-component asap, so uglyyyy

2024-02-16 23:22 UTC, KobieHazon commented on frontend/src/components/DevicesContainer/DevicesContainer.tsx
> +    <div className="table-container">
nooo, use a mui component for this use case it will be much better

2024-02-16 23:22 UTC, KobieHazon commented on frontend/src/components/DevicesContainer/DevicesContainer.tsx
> +const DevicesContainer = () => {
make a regular function component and export it instead

2024-02-16 23:22 UTC, KobieHazon commented on frontend/src/components/DevicesOSPieChart/DevicesOSPieChart.tsx
> +  const series = [
this is fake data right? the real one will make an api call to the backend for it?

2024-02-16 23:22 UTC, KobieHazon commented on frontend/src/components/DevicesOSPieChart/DevicesOSPieChart.tsx
> +const DeviceOSPieChart = () => {
make function component without lambda funcs

2024-02-17 13:25 UTC, ShaharBand commented on frontend/src/components/DevicesOSPieChart/DevicesOSPieChart.tsx
> +  const series = [
yes i plan on using some sort of javascript fetch with session validation or JWT token ish solution..

2024-02-17 13:29 UTC, KobieHazon commented on frontend/src/components/DevicesOSPieChart/DevicesOSPieChart.tsx
> +  const series = [
The validation should almost always be in the backend

2024-03-04 18:58 UTC, KobieHazon reviewed
Have fun :)

2024-03-04 18:58 UTC, KobieHazon commented on README.md
Your readme is pretty neat

2024-03-04 18:58 UTC, KobieHazon commented on README.md
can resolve

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/controllers/devices.py
> +        devices = await self.device_model.get_all_devices()
Design challenge: what if there are several ways to get the devices of a model and you want to configure it from the controller and do a round-robin between them, I think you will need to change it.
Remember - decoupling is key

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/controllers/devices.py
> +from beanie import PydanticObjectId
wanna be a pro? 
import it only if TYPE_CHECKING

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/controllers/devices.py
> +    async def get_device(self, device_id: PydanticObjectId):
return typing, everywhere

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/entities/device.py
> +    last_update: datetime = Field(default_factory=default_datetime)
why not simply use the datetime now function as the factory?
it just calls it

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/entities/device.py
> +class Device(Document):
good job

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/entities/devices/linux.py
> +class LinuxDevice(Device):
Much nicer then before

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/utils/datetime_utils.py
> +    return datetime.datetime.now().strftime("%d-%m-%Y %H:%M:%S")
if it is internal, you should save it as string, time.time() is just as good and less memory :)

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/entities/user.py
> +    last_ip: IPvAnyAddress
last ip is the last used ip? 
better naming

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/repositories/device.py
> +DEVICE_CLASS_MAP = {
DEVICE_NAME_TO_TYPE is better and more pythonic

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/repositories/device.py
> +from src.dal.entities.devices import *
very very bad practice to import star, try to think why

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/repositories/device.py
> +    def create_device(device_data: dict) -> Device:
do typing for the device data

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/repositories/device.py
> +class DeviceRepository:
Just a thought:
Why not decouple the storage of devices from the device class itself and cache it here?

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/dal/repositories/device.py
> +class DeviceRepository:
It is a static class anyway, so it can just be a singleton for all the devices, very convenient

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/middleware/db.py
> +async def init_db():
good

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/utils/config.py
> +    DB_USERNAME: str = "sentinel_db"
Separate to different objects :)
What if I run in multiple environments synced with different db's

2024-03-04 18:58 UTC, KobieHazon commented on backend/src/utils/mongodb_create_user.py
> +from pymongo import MongoClient
This file is a test?
if yes then just do a scratch file in pycharm or code, not in repo

2024-03-26 11:14 UTC, ShaharBand commented on backend/src/utils/config.py
> +class AppConfigManager:
i implemented a new config archtiecture inside a config folder seperating the db, app and environments from each other.

2024-03-26 11:16 UTC, ShaharBand commented on backend/src/dal/devices.py
> +    if config.MOCK_DB:
the configuration now is environment based...

2024-03-26 11:16 UTC, ShaharBand commented on backend/src/dal/users.py
> +# TODO: mock db
the configuration now is environment based...

2024-03-26 11:17 UTC, ShaharBand commented on backend/src/models/devices/device.py
> +    def id(self) -> int | None:
outdated

2024-03-26 11:17 UTC, ShaharBand commented on backend/src/models/devices/device.py
> +    @abstractmethod
outdated

2024-03-26 11:18 UTC, ShaharBand commented on backend/src/models/devices/windows_device.py
> +        query = (db.devices.id == self.id)
outdated

2024-03-26 11:19 UTC, ShaharBand commented on backend/src/models/devices/windows_device.py
> +            inserted_id = db.devices.insert(**dict(self.data))
outdated

2024-03-26 12:20 UTC, ShaharBand commented on backend/src/routers/users.py
> +router = APIRouter()
done

2024-03-27 14:36 UTC, ShaharBand commented on backend/src/controllers/devices.py
> +from beanie import PydanticObjectId
thank you very nice tip, changed.

2024-03-27 14:39 UTC, ShaharBand commented on backend/src/controllers/devices.py
> +from beanie import PydanticObjectId
something i find confusing what should i do if i have several imports that meant for type_checking however they have different import level usually we seperate to 3 categories python libraries, external libraries, personal/project imports but now i can have an if statement with different layers of imports i.e.:

`from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from beanie import PydanticObjectId

    from src.dal.entities.device import Device

from src.models.device import DeviceModel
`

do i put spaces like here? or do i just bundle them

2024-03-27 14:43 UTC, ShaharBand commented on backend/src/controllers/devices.py
> +    async def get_device(self, device_id: PydanticObjectId):
its a shame to have such mistake in my pretty code, i belong to the streets T_T

changed and fixed with type checking..

2024-03-27 14:45 UTC, ShaharBand commented on backend/src/dal/entities/device.py
> +    last_update: datetime = Field(default_factory=default_datetime)
changed

2024-03-27 14:48 UTC, ShaharBand commented on backend/src/dal/entities/devices/linux.py
> +class LinuxDevice(Device):
thank you very much can resolve?

2024-03-27 14:48 UTC, ShaharBand commented on backend/src/dal/entities/device.py
> +class Device(Document):
thank you very much can resolve?

2024-03-27 14:52 UTC, ShaharBand commented on backend/src/dal/repositories/device.py
> +DEVICE_CLASS_MAP = {
changed

2024-03-27 14:53 UTC, ShaharBand commented on backend/src/dal/repositories/device.py
> +class DeviceRepository:
thank you very much can resolve?

2024-03-27 14:54 UTC, ShaharBand commented on backend/src/middleware/db.py
> +async def init_db():
thank you very much can resolve?

2024-03-27 15:02 UTC, ShaharBand commented on backend/src/utils/config.py
> +    VERSION: str = "0.0.1"
i changed the configuration but i wonder what you mean by that where should version be stored then? i have a file called version for now took inspiration from git repo you recommended me

2024-03-27 15:02 UTC, ShaharBand commented on backend/src/utils/config.py
> +    DB_USERNAME: str = "sentinel_db"
done

2024-03-27 15:05 UTC, ShaharBand commented on backend/src/models/device.py
> +class DeviceModel:
:) resolve please

2024-03-27 15:06 UTC, ShaharBand commented on backend/src/utils/mongodb_create_user.py
> +from pymongo import MongoClient
done, didnt know about this one i moved it into a scratch file very nice feature..

2024-03-28 10:12 UTC, ShaharBand commented on backend/src/models/user.py
> +    def __init__(self, **args):
outdated but i will try to avoid kwargs

2024-03-28 10:23 UTC, ShaharBand commented on backend/src/dal/repositories/device.py
> +from src.dal.entities.devices import *
i see there is a possible issue with conflicting code overriding functions and debugging such case can be difficult..
changed it

2024-03-28 10:37 UTC, ShaharBand commented on backend/src/dal/repositories/device.py
> +    def create_device(device_data: dict) -> Device:
can you provide an example i could approach this in many ways

i could try some sort of typeddict, __init__ func given a dict with validation of my own code etc..

2024-03-28 12:50 UTC, ShaharBand commented on backend/src/dal/repositories/device.py
> +                setattr(device, key, value)
changed

2024-04-05 20:30 UTC, KobieHazon commented on backend/src/controllers/devices.py
> +from beanie import PydanticObjectId
You should put the functional imports first in the top of the file and afterwards, put the if TYPE_CHECKING statement with everything for the type checking inside. Inside the if it should be with empty lines between the different categories.

2024-04-05 20:30 UTC, KobieHazon commented on backend/src/controllers/devices.py
> +    async def get_device(self, device_id: PydanticObjectId):
hhhhhhh

2024-04-05 20:55 UTC, KobieHazon reviewed
The code is very nice and got a lot better, at this point, I would focus on adding functionality to the code instead of refactoring it over and over again. It will teach you more because you need more "meat" on it.

2024-04-05 20:55 UTC, KobieHazon commented on backend/main.py
> +    uvicorn.run("main:app", reload=True, host=app_config.IP, port=app_config.PORT)
Pro tip: you can configure uvicorn to run the backend multiprocessed and with threading, so you can get from the system how many cores and threads you have and tell that to uvicorn for it to do it all by itself.

2024-04-05 20:55 UTC, KobieHazon commented on backend/src/config/app.py
> +    IP: str = "127.0.0.1"
dont do it uppercase, it is not a constant value, it is configuration

2024-04-05 20:55 UTC, KobieHazon commented on backend/src/config/environment.py
> +class Environment(str, Enum):
dont know the python version but above 3.11 it has StrEnum

2024-04-05 20:55 UTC, KobieHazon commented on backend/src/controllers/devices.py
> +    from beanie import PydanticObjectId
Like I wrote in the general comment

2024-04-05 20:55 UTC, KobieHazon commented on backend/src/dal/repositories/device.py
> +    def create_device(device_data: dict) -> Device:
most times typeddict is an overkill, I would simply dict[key type, value type], if the keys are all strings it should be string and if the values have more then 2 possible types than I would probably just write any for readability.

2024-04-07 08:44 UTC, ShaharBand commented on backend/src/controllers/devices.py
> +from beanie import PydanticObjectId
updated

2024-04-07 08:45 UTC, ShaharBand commented on frontend/src/components/DevicesContainer/DevicesContainer.tsx
> +    <div className="table-container">
done

2024-04-14 13:22 UTC, ShaharBand commented on backend/src/config/environment.py
> +class Environment(str, Enum):
i like that there is such things i didnt know about this however after further investigation i think normal enum will be better because the entire purpose of this enum instead of a normal string is to make the code stupid proof this way normal is more strict and requires the programmer to use enum as i intended

2024-04-14 13:23 UTC, ShaharBand commented on backend/src/config/app.py
> +    IP: str = "127.0.0.1"
changed

2024-04-14 13:24 UTC, ShaharBand commented on backend/src/config/app.py
> +    IP: str = "127.0.0.1"
it is somesort of a constant tho? why would i change my ip in runtime or through the code

2024-04-15 06:35 UTC, ShaharBand commented on backend/main.py
> +    uvicorn.run("main:app", reload=True, host=app_config.IP, port=app_config.PORT)
done

2024-04-15 06:35 UTC, ShaharBand commented on backend/src/controllers/devices.py
> +    from beanie import PydanticObjectId
done

2024-04-15 07:57 UTC, ShaharBand commented on backend/main.py
> +    uvicorn.run("main:app", reload=True, host=app_config.IP, port=app_config.PORT)
i added a separation between uvicorn and fastapi for more abstraction and cleaner code main.py and run.py respectivly

2024-06-12 01:11 UTC, closed without merging